"""Add details to UnderwritingIssue

Revision ID: d545bc9dd84b
Revises: 954caae8332b
Create Date: 2026-09-28 11:11:40.552896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd545bc9dd84b'
down_revision: Union[str, Sequence[str], None] = '954caae8332b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('underwriting_issues', sa.Column('details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('underwriting_issues', 'details')
    # ### end Alembic commands ###
