import { useEffect, useState } from 'react';
import { api, type UserProfile } from '../services/api';

export default function ProfilePage() {
  const [profile, setProfile] = useState<UserProfile | null>(null); const [error, setError] = useState(''); const [saved, setSaved] = useState(false); const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState('');
  useEffect(() => { api.getProfile().then(setProfile).catch(() => setError('Unable to load your profile.')); }, []);
  if (!profile) return <div className="page"><section className="panel"><p>{error || 'Loading profile…'}</p></section></div>;
  const update = async (event: React.FormEvent) => { event.preventDefault(); setError(''); setSaved(false); try { const result = await api.updateProfile({ name: profile.name, phone: profile.phone || undefined, organization: profile.organization || undefined, job_title: profile.job_title || undefined, current_password: currentPassword || undefined, new_password: newPassword || undefined }); setProfile(result); setCurrentPassword(''); setNewPassword(''); setSaved(true); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to save your profile.'); } };
  return <div className="page"><section className="panel form-surface"><p className="auth-eyebrow">{profile.role} account</p><h1>Your profile</h1><p className="subtitle">Keep your contact and organisation details current.</p>{error && <div className="error-box">{error}</div>}{saved && <p className="success-text">Profile saved.</p>}<form className="form-grid" onSubmit={update}><div className="field-group"><label>Email address</label><input value={profile.email} disabled /></div><div className="field-group"><label>Full name</label><input value={profile.name} onChange={(e) => setProfile({ ...profile, name: e.target.value })} required /></div><div className="field-group"><label>Organisation</label><input value={profile.organization || ''} onChange={(e) => setProfile({ ...profile, organization: e.target.value })} /></div><div className="field-group"><label>Role title</label><input value={profile.job_title || ''} onChange={(e) => setProfile({ ...profile, job_title: e.target.value })} /></div><div className="field-group"><label>Phone number</label><input type="tel" value={profile.phone || ''} onChange={(e) => setProfile({ ...profile, phone: e.target.value })} /></div><div className="field-group"><label>Current password</label><input type="password" value={currentPassword} onChange={(e) => setCurrentPassword(e.target.value)} /></div><div className="field-group"><label>New password</label><input type="password" value={newPassword} onChange={(e) => setNewPassword(e.target.value)} /></div><div className="form-actions full"><span></span><button className="btn-primary">Save profile</button></div></form></section></div>;
}
