import { useCallback, useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { api } from '../services/api';

const labels: Record<string, string> = { company_name:'Company name', business_type:'Business type', industry:'Industry', years_in_operation:'Years in operation', business_address:'Business address', city:'City', state:'State', country:'Country', annual_revenue:'Annual revenue', property_address:'Property address', property_type:'Property type', property_value:'Approximate property value', ownership_type:'Property ownership', property_operations:'Property operations', employee_count:'Number of employees', hazardous_materials:'Hazardous materials', risk_level:'Risk level', insured_name:'Insured name' };
const label = (key: string) => labels[key] || 'Evidence item';
const evidenceSourceLabel = (source: string) => source === 'answer' ? 'Application' : source.startsWith('document_') ? 'Supporting document' : 'Supporting evidence';
const status = (value: string) => ({ draft:'Draft', under_review:'Under review', info_requested:'Information required', approved:'Approved', declined:'Declined' }[value] || value.replaceAll('_',' '));
type Tab = 'overview'|'evidence'|'issues'|'requirements'|'history';
export default function SubmissionDetail() {
 const {submissionId}=useParams(); const navigate=useNavigate(); const [data,setData]=useState<any>(); const [error,setError]=useState(''); const [note,setNote]=useState(''); const [tab,setTab]=useState<Tab>('overview'); const [requestType,setRequestType]=useState<'information'|'document'>('information'); const [requestName,setRequestName]=useState(''); const [requestMessage,setRequestMessage]=useState(''); const [pending,setPending]=useState('');
 const refresh=useCallback(()=>api.getDashboardSummary(Number(submissionId)).then(setData).catch(()=>setError('Unable to load this submission. Please try again.')),[submissionId]); useEffect(()=>{refresh()},[refresh]);
 if(error)return <div className="page"><div className="error-box" role="alert">{error}</div><button className="btn-secondary" onClick={refresh}>Try again</button></div>; if(!data)return <div className="page"><section className="panel"><p className="subtitle">Loading underwriting workspace…</p></section></div>;
 const {submission,application_profile:profile,answers,documents,consistency_checks:checks,issues,requirements,audit_trail:history}=data;
 const activeIssues=issues.filter((item:any)=>item.status==='open'); const completedIssues=issues.filter((item:any)=>item.status!=='open');
 const action=async(kind:'approved'|'declined')=>{if(!window.confirm(`Confirm ${kind === 'approved' ? 'approval' : 'decline'}? This decision cannot be changed.`))return; setPending(kind);try{await api.updateSubmissionStatus(Number(submissionId),kind,note);setNote('');refresh()}catch{setError('Unable to record this decision.')}finally{setPending('')}};
 const issue=async(id:number,kind:string)=>{setPending(`issue-${id}`);try{await api.updateIssueStatus(Number(submissionId),id,kind,note);setNote('');refresh()}catch{setError('Unable to update this review item.')}finally{setPending('')}};
 const request=async()=>{setPending('request');try{await api.createAdditionalRequest(Number(submissionId),{type:requestType,document_name:requestName||undefined,message:requestMessage,note:note||undefined});setRequestMessage('');setRequestName('');setNote('');refresh()}catch{setError('Unable to send this request.')}finally{setPending('')}};
 const tabs: {id:Tab;name:string}[]=[{id:'overview',name:'Overview'},{id:'evidence',name:'Evidence & documents'},{id:'issues',name:'Issues'},{id:'requirements',name:'Requirements'},{id:'history',name:'History'}];
 return <div className="page detail-page"><button className="link-btn" onClick={()=>navigate('/underwriter')}>← Back to queue</button><header className="panel workspace-header"><div><h1>{submission.product_name} application</h1><p className="subtitle">{submission.applicant} · Submitted {new Date(submission.created_at).toLocaleString()}</p>{submission.insurance_company&&<p className="submission-meta">Insurer: {submission.insurance_company}{submission.assigned_underwriter ? ` · Assigned underwriter: ${submission.assigned_underwriter}` : ''}</p>}</div><span className={`badge status-${submission.status}`}>{status(submission.status)}</span></header><nav className="workspace-tabs" aria-label="Submission sections">{tabs.map(item=><button key={item.id} className={tab===item.id?'active':''} onClick={()=>setTab(item.id)}>{item.name}</button>)}</nav><div className="workspace-grid"><main>
 {tab==='overview'&&<section className="panel"><h2>Applicant, business and property</h2><Details data={profile}/><h2>Risk information</h2>{answers.length?<dl className="review-details">{answers.map((a:any,i:number)=><Pair key={i} name={a.label} value={a.value}/>)}</dl>:<p className="empty">No risk responses have been recorded.</p>}</section>}
 {tab==='evidence'&&<section className="panel"><h2>Documents and evidence</h2>{documents.filter((d:any)=>!d.replaced).length?documents.filter((d:any)=>!d.replaced).map((doc:any)=><article className="document-card" key={doc.id}><div className="document-card-header"><strong>{doc.name}</strong><span className="badge">{doc.status==='processed'?'Information extracted':doc.status}</span></div><button className="link-btn" onClick={()=>api.viewDocument(doc.id)}>Open document</button>{doc.extracted_fields.length?<dl className="review-details">{doc.extracted_fields.map((f:any,i:number)=><Pair key={i} name={f.label||label(f.key)} value={f.value||f.normalized_value||f.raw_value}/>)}</dl>:<p className="empty">No information was extracted from this document.</p>}</article>):<p className="empty">No documents have been uploaded.</p>}<h2>Consistency findings</h2>{checks.length?checks.map((check:any,i:number)=><article className="issue-card" key={i}><strong>{label(check.details?.canonical_key||'')} · {check.status==='CONFLICT'?'Needs review':check.status==='INSUFFICIENT_EVIDENCE'?'More evidence needed':'Verified'}</strong><p>{check.details?.reason||(check.details?.reasons||[]).join(' ')||'Evidence was evaluated.'}</p>{check.status==='CONFLICT'&&<p><strong>Suggested action:</strong> Request clarification.</p>}</article>):<p className="empty">No consistency findings yet.</p>}</section>}
 {tab==='issues'&&<section className="panel"><div className="issue-section-heading"><div><h2>Underwriting issues</h2><p className="subtitle">{activeIssues.length} active {activeIssues.length===1?'suggestion':'suggestions'} requiring review.</p></div>{activeIssues.length===0&&<span className="badge badge-success">Review complete</span>}</div>{activeIssues.length?activeIssues.map((item:any)=><IssueCard key={item.id} item={item} pending={pending} onAction={issue}/>):<section className="review-complete"><h3>All review suggestions are complete</h3><p>You can now record a final decision or request more information from the applicant.</p></section>}{completedIssues.length>0&&<details className="completed-issues"><summary>Resolved and dismissed suggestions ({completedIssues.length})</summary>{completedIssues.map((item:any)=><IssueCard key={item.id} item={item} pending={pending} onAction={issue}/>)}</details>}</section>}
 {tab==='requirements'&&<section className="panel"><h2>Requirements</h2>{requirements.map((r:any)=><article className="issue-card" key={r.requirement_id}><strong>{r.fulfilled?'Verified':'Outstanding'} · {r.name}</strong><p>{r.explanation}</p></article>)}</section>}
 {tab==='history'&&<section className="panel"><h2>Submission history</h2>{history.length?history.map((event:any)=><article className="audit-event" key={event.id}><div className="audit-time">{event.timestamp&&new Date(event.timestamp).toLocaleString()}</div><strong>{event.action.replaceAll('_',' ')}</strong>{event.context_data?.actor_role&&<small> · {event.context_data.actor_role}</small>}{event.context_data?.note&&<p>“{event.context_data.note}”</p>}</article>):<p className="empty">No history is available yet.</p>}</section>}
 </main><aside className="side-col"><section className="panel"><h2>Review decision</h2><textarea aria-label="Optional review note" placeholder="Optional review note" value={note} onChange={e=>setNote(e.target.value)}/>{submission.status==='under_review'?activeIssues.length?<p className="empty">Resolve or dismiss the {activeIssues.length} active review {activeIssues.length===1?'suggestion':'suggestions'} before recording a final decision.</p>:<><p className="success-text">Review complete. Record the underwriting decision when ready.</p><div className="form-actions"><button className="btn-primary" disabled={!!pending} onClick={()=>action('approved')}>{pending==='approved'?'Saving…':'Approve application'}</button><button className="btn-danger" disabled={!!pending} onClick={()=>action('declined')}>{pending==='declined'?'Saving…':'Decline application'}</button></div></>:<p className="empty">This application is not awaiting a decision.</p>}</section><section className="panel"><h2>Request more information</h2>{submission.status==='under_review'?<><select aria-label="Request type" value={requestType} onChange={e=>setRequestType(e.target.value as 'information'|'document')}><option value="information">Information</option><option value="document">Document</option></select>{requestType==='document'&&<input aria-label="Requested document name" placeholder="Requested document name" value={requestName} onChange={e=>setRequestName(e.target.value)}/>}<textarea placeholder="Explain what is needed" value={requestMessage} onChange={e=>setRequestMessage(e.target.value)}/><button className="btn-secondary" disabled={!!pending||!requestMessage||(requestType==='document'&&!requestName)} onClick={request}>{pending==='request'?'Sending…':'Send request'}</button></>:<p className="empty">Requests can be created while under review.</p>}</section></aside></div></div>;
}
function Pair({name,value}:{name:string;value:unknown}){return <><dt>{name}</dt><dd>{String(value)}</dd></>}; function Details({data}:{data:Record<string,unknown>}){const rows=Object.entries(data||{}).filter(([,value])=>value!==null&&value!=='');return rows.length?<dl className="review-details">{rows.map(([key,value])=><Pair key={key} name={label(key)} value={value}/>)}</dl>:<p className="empty">No application details have been provided.</p>}
function IssueCard({item,pending,onAction}:{item:any;pending:string;onAction:(id:number,action:string)=>void}){const evidence=(item.details?.sources||[]).filter(Boolean).map(evidenceSourceLabel).filter((value:string,index:number,all:string[])=>all.indexOf(value)===index);return <article className="issue-card"><p className="issue-category">{item.details?.display_category||item.issue_type?.replaceAll('_',' ')||'Underwriting issue'}</p><h3>{item.details?.summary||item.description}</h3><p><b>Why this matters:</b> {item.details?.reason||'The available evidence needs underwriting review.'}</p>{evidence.length>0&&<p><b>Evidence reviewed:</b> {evidence.join(', ')}</p>}<p><b>Recommended next step:</b> {item.details?.recommended_action||'Review the available evidence.'}</p><span className="badge">{item.status==='resolved'?'Resolved':item.status==='dismissed'?'Dismissed':item.status}</span>{item.status==='open'&&<p className="issue-actions"><button className="btn-sm" disabled={!!pending} onClick={()=>onAction(item.id,'resolve')}>Accept suggestion</button> <button className="btn-sm btn-outline" disabled={!!pending} onClick={()=>onAction(item.id,'dismiss')}>Dismiss</button></p>}</article>}
