import { useCallback, useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { api } from '../services/api';

const labels: Record<string, string> = { company_name: 'Company name', business_type: 'Business type', industry: 'Industry', years_in_operation: 'Years in operation', business_address: 'Business address', city: 'City', state: 'State', country: 'Country', annual_revenue: 'Annual revenue', property_address: 'Property address', property_type: 'Property type', property_value: 'Approximate property value', ownership_type: 'Property ownership', property_operations: 'Property operations', employee_count: 'Number of employees', hazardous_materials: 'Hazardous materials', risk_level: 'Risk level', insured_name: 'Insured name' };
const label = (key: string) => labels[key] || 'Evidence item';
const status = (value: string) => ({ draft: 'Draft', under_review: 'Under review', info_requested: 'Information requested', approved: 'Approved', declined: 'Declined' }[value] || value.replaceAll('_', ' '));

export default function SubmissionDetail() {
  const { submissionId } = useParams(); const navigate = useNavigate();
  const [data, setData] = useState<any>(); const [error, setError] = useState(''); const [note, setNote] = useState('');
  const [requestType, setRequestType] = useState<'information' | 'document'>('information'); const [requestName, setRequestName] = useState(''); const [requestMessage, setRequestMessage] = useState('');
  const refresh = useCallback(() => api.getDashboardSummary(Number(submissionId)).then(setData).catch((e) => setError(e.message)), [submissionId]);
  useEffect(() => { refresh(); }, [refresh]);
  if (error) return <div className="page"><div className="error-box">{error}</div></div>;
  if (!data) return <div className="page"><p>Loading submission review…</p></div>;
  const { submission, application_profile: profile, answers, documents, consistency_checks: checks, issues, requirements, audit_trail: history } = data;
  const doIssue = async (id: number, action: string) => { await api.updateIssueStatus(Number(submissionId), id, action, note); setNote(''); refresh(); };
  const doStatus = async (next: string) => { await api.updateSubmissionStatus(Number(submissionId), next, note); setNote(''); refresh(); };
  const requestMore = async () => { await api.createAdditionalRequest(Number(submissionId), { type: requestType, document_name: requestName || undefined, message: requestMessage, note: note || undefined }); setRequestMessage(''); setRequestName(''); setNote(''); refresh(); };
  return <div className="page detail-page"><button className="link-btn" onClick={() => navigate('/underwriter')}>← Underwriter queue</button>
    <section className="panel"><h1>{submission.product_name} application</h1><p>{submission.applicant} · Submitted {new Date(submission.created_at).toLocaleString()}</p><span className="badge">{status(submission.status)}</span></section>
    <div className="dashboard-grid"><div className="main-col">
      <section className="panel"><h2>Applicant, business and property</h2><Details data={profile} /><h3>Risk information</h3>{answers.length ? <dl className="review-details">{answers.map((a: any, i: number) => <Pair key={i} name={a.label} value={a.value} />)}</dl> : <p className="empty">No risk responses recorded.</p>}</section>
      <section className="panel"><h2>Documents and evidence</h2>{documents.filter((d: any) => !d.replaced).map((doc: any) => <div className="document-card" key={doc.id}><div className="document-card-header"><strong>{doc.name}</strong><span className="badge">{doc.status === 'processed' ? 'Processed' : doc.status}</span></div><button className="link-btn" onClick={() => api.viewDocument(doc.id)}>Open document</button>{doc.extracted_fields.length ? <dl className="review-details">{doc.extracted_fields.map((f: any, i: number) => <Pair key={i} name={f.label || label(f.key)} value={f.value || f.normalized_value || f.raw_value} />)}</dl> : <p className="empty">No information extracted.</p>}</div>) || <p className="empty">No documents uploaded.</p>}</section>
      <section className="panel"><h2>Evidence consistency</h2>{checks.length ? checks.map((check: any, i: number) => <div className="issue-card" key={i}><strong>{label(check.details?.canonical_key || '')} {check.status === 'CONFLICT' ? 'mismatch' : check.status === 'INSUFFICIENT_EVIDENCE' ? 'needs more evidence' : 'check'}</strong><p>{check.details?.reason || (check.details?.reasons || []).join(' ') || 'Evidence was evaluated.'}</p>{check.status === 'CONFLICT' && <p><strong>Suggested action:</strong> Request clarification.</p>}</div>) : <p className="empty">No consistency checks have been recorded yet.</p>}</section>
      <section className="panel"><h2>Underwriting issues</h2>{issues.length ? issues.map((issue: any) => <div className="issue-card" key={issue.id}><strong>{issue.description}</strong><p>{issue.details?.reason || issue.details?.recommended_action || 'Review the available evidence.'}</p><p>Status: {issue.status}</p>{issue.status === 'open' && <><button className="btn-sm btn-success" onClick={() => doIssue(issue.id, 'resolve')}>Accept suggestion</button><button className="btn-sm btn-outline" onClick={() => doIssue(issue.id, 'dismiss')}>Dismiss</button></>}</div>) : <p className="empty">No underwriting issues identified.</p>}</section>
    </div><aside className="side-col"><section className="panel"><h2>Review action</h2><textarea placeholder="Optional review note" value={note} onChange={(e) => setNote(e.target.value)} />{submission.status === 'under_review' && <div className="decision-buttons"><button className="btn-primary" onClick={() => doStatus('approved')}>Approve</button><button className="btn-danger" onClick={() => doStatus('declined')}>Decline</button></div>}</section><section className="panel"><h2>Request more information</h2>{submission.status === 'under_review' ? <><select value={requestType} onChange={(e) => setRequestType(e.target.value as 'information' | 'document')}><option value="information">Information</option><option value="document">Document</option></select>{requestType === 'document' && <input placeholder="Document name" value={requestName} onChange={(e) => setRequestName(e.target.value)} />}<textarea placeholder="Explain what is needed" value={requestMessage} onChange={(e) => setRequestMessage(e.target.value)} /><button className="btn-secondary" disabled={!requestMessage || (requestType === 'document' && !requestName)} onClick={requestMore}>Send request</button></> : <p className="empty">Requests can be created while the application is under review.</p>}</section><section className="panel"><h2>Requests and responses</h2>{(data.additional_requests || []).map((request: any) => <div className="audit-event" key={request.id}><strong>{request.type === 'document' ? request.document_name : 'Information request'}</strong><p>{request.message}</p><small>{request.status === 'satisfied' ? 'Customer responded' : 'Awaiting customer response'}</small></div>)}</section><section className="panel"><h2>Requirements</h2>{requirements.map((r: any) => <p key={r.requirement_id}>{r.fulfilled ? '✓' : '•'} {r.name}: {r.explanation}</p>)}</section><section className="panel"><h2>Submission history</h2>{history.map((event: any) => <div className="audit-event" key={event.id}><div className="audit-time">{event.timestamp && new Date(event.timestamp).toLocaleString()}</div><div>{event.action.replaceAll('_', ' ')}</div>{event.context_data?.actor_role && <small>{event.context_data.actor_role}</small>}{event.context_data?.note && <p>“{event.context_data.note}”</p>}</div>)}</section></aside></div></div>;
}
function Pair({ name, value }: { name: string; value: unknown }) { return <><dt>{name}</dt><dd>{String(value)}</dd></>; }
function Details({ data }: { data: Record<string, unknown> }) { const rows = Object.entries(data || {}).filter(([, value]) => value !== null && value !== ''); return rows.length ? <dl className="review-details">{rows.map(([key, value]) => <Pair key={key} name={label(key)} value={value} />)}</dl> : <p className="empty">No application details have been provided.</p>; }
